// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-CDh3KQZBVN2eki1h2MCXNV9jBMO0wg',
    appId: '1:511301026544:web:1d03e6d63e4cac7b89b835',
    messagingSenderId: '511301026544',
    projectId: 'bussiness-mobile-app',
    authDomain: 'bussiness-mobile-app.firebaseapp.com',
    storageBucket: 'bussiness-mobile-app.appspot.com',
    measurementId: 'G-VQFLJ74R1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBffcbx6U8caRB2-VgWdAUzGxpkcJkU-UQ',
    appId: '1:511301026544:android:1e8e154638169dcf89b835',
    messagingSenderId: '511301026544',
    projectId: 'bussiness-mobile-app',
    storageBucket: 'bussiness-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfbgMk4U72X23XDKl2-YAplLlPxLgdyck',
    appId: '1:511301026544:ios:0973f5c17316720489b835',
    messagingSenderId: '511301026544',
    projectId: 'bussiness-mobile-app',
    storageBucket: 'bussiness-mobile-app.appspot.com',
    iosBundleId: 'com.example.bussinessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfbgMk4U72X23XDKl2-YAplLlPxLgdyck',
    appId: '1:511301026544:ios:4bdb391249e6ccc289b835',
    messagingSenderId: '511301026544',
    projectId: 'bussiness-mobile-app',
    storageBucket: 'bussiness-mobile-app.appspot.com',
    iosBundleId: 'com.example.bussinessApp.RunnerTests',
  );
}
